

-------------------------------------------------------------------------
Systeminfo:
CPU:               Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Number of CPUs:    8
RAM:               31.9GB
Diskinfo:          25.7GB/446.5GB
Operating system:  Windows-10-10.0.19045
Long path support: False
-------------------------------------------------------------------------

= 31.10.2024 18:05:47 (UTC +0:00) === ecu.test 2024.3.0.156114+c108ea21784a 156114+c108ea21784a (2024/09/19 12:15:31) (64bit) ===
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] / wx: 4.2.1+tt.5
Protocol: log level Default. Additional logging active: default output

License: ecu.test
         - License options:
             + ecu.test diagnostics
         - valid up to version: 2024.4
         - valid until: 2025-01-28
         - licensed for: Mahindra_Racing_UK
         - runner: False
         - Server: license01.tracetronic.de



2024-10-31 18:05:47.456 15240 ManagedWorker-7*PE.Run() ERROR:
                        Traceback (most recent call last):
                          File "tts\core\toolingFramework\toolAccess\LockProxy.py", line 57, in __call__
                          File "tts\core\toolingFramework\interface\Proxy.py", line 70, in __call__
                          File "tts\core\toolingFramework\userTool\adapters\UserToolAdapter.py", line 133, in ExecuteJob
                          File "C:\Users\DIL\ecu.test\Workspace\Utilities\SM\SM_Adapter.py", line 165, in Reprogram_App
                            (res, ValResult) = self.sm.Reprogram(AppNo+12800)
                            ^^^^^^^^^^^^^^^^
                        TypeError: cannot unpack non-iterable int object
                        
                        The above exception was the direct cause of the following exception:
                        
                        Traceback (most recent call last):
                          File "tts\testExecution\testSteps\generic\TestStepJobExec.py", line 186, in __Call
                          File "tts\core\mapping\xa\XAJobExec.py", line 83, in Call
                          File "tts\core\toolingFramework\toolAccess\LockProxy.py", line 76, in __call__
                          File "tts\core\toolingFramework\toolAccess\LockProxy.py", line 89, in ReportToolError
                        tts.core.toolingFramework.toolAccess.Exceptions.ToolError: Tool 01_McLaren_SM01 (@local): ExecuteJob() failed: cannot unpack non-iterable int object
2024-10-31 18:05:47.492 15240 ManagedWorker-7*PE.Run() DEBUG_EXC_PRINT:
                        Traceback (most recent call last):
                          File "tts\testExecution\engine\TestEngine.py", line 923, in ExecuteTestStep
                          File "tts\testExecution\testSteps\generic\TestStepJobExec.py", line 265, in Run
                        tt._Exceptions_.TTError: Tool 01_McLaren_SM01 (@local): ExecuteJob() failed: cannot unpack non-iterable int object
2024-10-31 18:05:47.808 15240 ManagedWorker-7*PE.Run() ERROR:
                        Traceback (most recent call last):
                          File "tts\core\toolingFramework\toolAccess\LockProxy.py", line 57, in __call__
                          File "tts\core\toolingFramework\interface\Proxy.py", line 70, in __call__
                          File "tts\core\toolingFramework\userTool\adapters\UserToolAdapter.py", line 133, in ExecuteJob
                          File "C:\Users\DIL\ecu.test\Workspace\Utilities\SM\SM_Adapter.py", line 165, in Reprogram_App
                            (res, ValResult) = self.sm.Reprogram(AppNo+12800)
                            ^^^^^^^^^^^^^^^^
                        TypeError: cannot unpack non-iterable int object
                        
                        The above exception was the direct cause of the following exception:
                        
                        Traceback (most recent call last):
                          File "tts\testExecution\testSteps\generic\TestStepJobExec.py", line 186, in __Call
                          File "tts\core\mapping\xa\XAJobExec.py", line 83, in Call
                          File "tts\core\toolingFramework\toolAccess\LockProxy.py", line 76, in __call__
                          File "tts\core\toolingFramework\toolAccess\LockProxy.py", line 89, in ReportToolError
                        tts.core.toolingFramework.toolAccess.Exceptions.ToolError: Tool 01_McLaren_SM01 (@local): ExecuteJob() failed: cannot unpack non-iterable int object
2024-10-31 18:05:47.842 15240 ManagedWorker-7*PE.Run() DEBUG_EXC_PRINT:
                        Traceback (most recent call last):
                          File "tts\testExecution\engine\TestEngine.py", line 923, in ExecuteTestStep
                          File "tts\testExecution\testSteps\generic\TestStepJobExec.py", line 265, in Run
                        tt._Exceptions_.TTError: Tool 01_McLaren_SM01 (@local): ExecuteJob() failed: cannot unpack non-iterable int object
